name: Manter Streamlit Acordado

on:
  schedule:
    # Executa a cada 6 horas automaticamente
    - cron: '0 */6 * * *'
  workflow_dispatch: 
    # Permite que você ative o robô manualmente com um clique para testar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping no servidor do Streamlit
        # Link sem a barra no final, disfarce de navegador Chrome (-A) e ignorador de erros (|| true)
        run: curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://perfil-termico-rodas-sgucdepziyz2rvhjhttkhp.streamlit.app > /dev/null || true
